### ISSUE TITLE
TypeError: Cannot match against 'undefined' or 'null'

### ISSUE THREAD

**Issue by kinglozzer** [voidcosmos/npkill#31]
**Describe the bug**
```
Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/lib/controller.js:267
            const { name, ctrl } = key;
                                   ^

TypeError: Cannot match against 'undefined' or 'null'.
    at ReadStream.process.stdin.on (/Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/lib/controller.js:267:36)
    at emitTwo (events.js:106:13)
    at ReadStream.emit (events.js:191:7)
    at emitKey (/Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/node_modules/keypress/index.js:406:12)
    at /Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/node_modules/keypress/index.js:363:7
    at String.forEach (native)
    at emitKey (/Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/node_modules/keypress/index.js:362:29)
    at ReadStream.onData (/Users/kinglozzer/.nvm/versions/node/v6.9.0/lib/node_modules/npkill/node_modules/keypress/index.js:48:14)
    at emitOne (events.js:96:13)
    at ReadStream.emit (events.js:188:7)
```

 - OS: MacOS 
 - Version: v0.4.3

**Additional context**

The scan was still running, the first ~10 items were all items I wanted to delete, so I hit down+space repeatedly without waiting

**Comment by zaldih** [comment]
Thank you for opening the issue!

It seems that stdin is not behaving as it should on your machine for some reason, but I don't understand the reason.
https://github.com/voidcosmos/npkill/blob/f7cc0918f2247ba6a9cc34fd4e64daf9d7a00e06/src/controller.ts#L367

- The crash happen immediately after pressing key down or after pressing pressing space?
- Does it also happen when you press any other key such as "g"?
- Could you try if the same thing happens in another terminal?

**Comment by kinglozzer** [comment]
I can’t actually reproduce it now, so let’s close this. Thanks!

**Comment by zaldih** [comment]
I'm happy to read that. Have a nice day!
